language: ruby
script: "rake spec"

before_install:
  - gem install bundler -v '~> 2.0'

bundler_args: --without yard guard benchmarks

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.0.5.0
  - jruby-9.1.5.0
  - jruby-9.1.6.0
  - jruby-9.2.1
  - ruby-head
  - truffleruby

env: JRUBY_OPTS="$JRUBY_OPTS --debug"

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: truffleruby
